import React, { useState } from 'react';
    import { useMaterials } from '../context/MaterialContext';
    import EmptyState from '../components/EmptyState';
    import { motion } from 'framer-motion';
    import { HelpCircle, CheckCircle, XCircle, Award, RotateCcw } from 'lucide-react';

    interface QuizQuestion {
      id: string;
      question: string;
      options: string[];
      correctAnswer: number;
    }

    export default function Quiz() {
      const { activeMaterial } = useMaterials();
      const [isGenerating, setIsGenerating] = useState(false);
      const [questions, setQuestions] = useState<QuizQuestion[]>([]);
      const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);
      const [selectedOption, setSelectedOption] = useState<number | null>(null);
      const [showResult, setShowResult] = useState(false);
      const [score, setScore] = useState(0);
      const [isFinished, setIsFinished] = useState(false);

      if (!activeMaterial) {
        return (
          <EmptyState 
            title="No Active Material" 
            description="You need to select or upload a study material first to generate an AI quiz."
          />
        );
      }

      const generateQuiz = () => {
        setIsGenerating(true);
        setTimeout(() => {
          setQuestions([
            {
              id: 'q1',
              question: `Based on "${activeMaterial.title}", what is the primary focus of the text?`,
              options: ['The historical context', 'The fundamental principles', 'Advanced applications', 'Unrelated trivia'],
              correctAnswer: 1
            },
            {
              id: 'q2',
              question: 'Which of the following best describes the significance of this material?',
              options: ['It is obsolete', 'It forms a foundational basis', 'It is purely theoretical', 'It is only for experts'],
              correctAnswer: 1
            },
            {
              id: 'q3',
              question: 'What type of concepts are primarily discussed?',
              options: ['Core conceptual theories', 'Mathematical equations', 'Biographical details', 'Fictional narratives'],
              correctAnswer: 0
            }
          ]);
          setIsGenerating(false);
          resetState();
        }, 2500);
      };

      const resetState = () => {
        setCurrentQuestionIdx(0);
        setSelectedOption(null);
        setShowResult(false);
        setScore(0);
        setIsFinished(false);
      };

      const handleSubmit = () => {
        if (selectedOption === null) return;
        
        const isCorrect = selectedOption === questions[currentQuestionIdx].correctAnswer;
        if (isCorrect) setScore(s => s + 1);
        
        setShowResult(true);
      };

      const handleNext = () => {
        if (currentQuestionIdx < questions.length - 1) {
          setCurrentQuestionIdx(prev => prev + 1);
          setSelectedOption(null);
          setShowResult(false);
        } else {
          setIsFinished(true);
        }
      };

      if (questions.length === 0) {
        return (
          <div className="max-w-4xl mx-auto pb-12">
            <div className="mb-8">
              <h1 className="text-3xl font-bold font-sans mb-2">Knowledge Quiz</h1>
              <p className="text-muted-foreground flex items-center">
                Generating from: <span className="font-medium text-foreground ml-1 truncate max-w-[200px] inline-block">{activeMaterial.title}</span>
              </p>
            </div>
            
            <div className="bg-card border border-border rounded-2xl p-12 text-center shadow-sm max-w-2xl mx-auto mt-12">
              <div className="w-16 h-16 bg-orange-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
                <HelpCircle className="w-8 h-8 text-orange-500" />
              </div>
              <h2 className="text-2xl font-bold mb-4">Generate Practice Quiz</h2>
              <p className="text-muted-foreground mb-8">
                Test your understanding of <strong>"{activeMaterial.title}"</strong> with a custom multiple-choice quiz generated by AI.
              </p>
              <button
                onClick={generateQuiz}
                disabled={isGenerating}
                className="px-8 py-3 bg-primary text-primary-foreground rounded-full font-medium hover:bg-primary/90 transition-all hover:shadow-lg disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center mx-auto w-full sm:w-auto"
              >
                {isGenerating ? (
                  <>
                    <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin mr-3" />
                    Crafting questions...
                  </>
                ) : (
                  <>
                    <HelpCircle className="w-5 h-5 mr-2" />
                    Start Quiz
                  </>
                )}
              </button>
            </div>
          </div>
        );
      }

      if (isFinished) {
        const percentage = Math.round((score / questions.length) * 100);
        return (
          <div className="max-w-2xl mx-auto pb-12 pt-8">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="bg-card border border-border rounded-2xl p-10 text-center shadow-md"
            >
              <Award className={`w-20 h-20 mx-auto mb-6 ${percentage >= 70 ? 'text-green-500' : 'text-orange-500'}`} />
              <h2 className="text-3xl font-bold font-sans mb-2">Quiz Completed!</h2>
              <p className="text-muted-foreground mb-8">Here's how you performed on this material.</p>
              
              <div className="flex justify-center items-end space-x-2 mb-8">
                <span className="text-6xl font-bold text-primary">{score}</span>
                <span className="text-2xl text-muted-foreground mb-1">/ {questions.length}</span>
              </div>
              
              <div className="w-full bg-secondary rounded-full h-3 mb-8 overflow-hidden">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${percentage}%` }}
                  transition={{ duration: 1, ease: "easeOut" }}
                  className={`h-full ${percentage >= 70 ? 'bg-green-500' : 'bg-orange-500'}`}
                />
              </div>

              <div className="flex gap-4 justify-center">
                <button 
                  onClick={resetState}
                  className="px-6 py-3 bg-secondary text-secondary-foreground font-medium rounded-lg hover:bg-secondary/80 transition-colors flex items-center"
                >
                  <RotateCcw className="w-4 h-4 mr-2" />
                  Try Again
                </button>
                <button 
                  onClick={generateQuiz}
                  className="px-6 py-3 bg-primary text-primary-foreground font-medium rounded-lg hover:bg-primary/90 transition-colors flex items-center"
                >
                  New Questions
                </button>
              </div>
            </motion.div>
          </div>
        );
      }

      const question = questions[currentQuestionIdx];

      return (
        <div className="max-w-3xl mx-auto pb-12">
          <div className="mb-8 flex items-center justify-between">
            <h1 className="text-2xl font-bold font-sans">Practice Quiz</h1>
            <span className="text-sm font-medium bg-secondary px-3 py-1 rounded-full text-secondary-foreground">
              Question {currentQuestionIdx + 1} of {questions.length}
            </span>
          </div>

          <div className="bg-card border border-border rounded-2xl shadow-sm overflow-hidden">
            <div className="p-6 md:p-8 border-b border-border bg-accent/30">
              <h2 className="text-xl md:text-2xl font-medium leading-relaxed">
                {question.question}
              </h2>
            </div>
            
            <div className="p-6 md:p-8 space-y-3">
              {question.options.map((option, idx) => {
                let borderClass = 'border-border';
                let bgClass = 'bg-background hover:bg-accent hover:border-primary/30';
                let icon = null;

                if (showResult) {
                  if (idx === question.correctAnswer) {
                    borderClass = 'border-green-500';
                    bgClass = 'bg-green-500/10';
                    icon = <CheckCircle className="w-5 h-5 text-green-500" />;
                  } else if (idx === selectedOption) {
                    borderClass = 'border-red-500';
                    bgClass = 'bg-red-500/10';
                    icon = <XCircle className="w-5 h-5 text-red-500" />;
                  } else {
                    bgClass = 'bg-background opacity-50';
                  }
                } else if (selectedOption === idx) {
                  borderClass = 'border-primary';
                  bgClass = 'bg-primary/5';
                }

                return (
                  <button
                    key={idx}
                    onClick={() => !showResult && setSelectedOption(idx)}
                    disabled={showResult}
                    className={`w-full text-left p-4 rounded-xl border-2 transition-all flex items-center justify-between ${borderClass} ${bgClass}`}
                  >
                    <span className="text-base font-medium">{option}</span>
                    {icon}
                  </button>
                );
              })}
            </div>

            <div className="p-6 bg-accent/20 border-t border-border flex justify-end">
              {!showResult ? (
                <button
                  onClick={handleSubmit}
                  disabled={selectedOption === null}
                  className="px-8 py-3 bg-primary text-primary-foreground font-medium rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Submit Answer
                </button>
              ) : (
                <button
                  onClick={handleNext}
                  className="px-8 py-3 bg-foreground text-background font-medium rounded-lg hover:bg-foreground/90 transition-colors flex items-center"
                >
                  {currentQuestionIdx < questions.length - 1 ? 'Next Question' : 'View Results'}
                  <RotateCcw className="w-4 h-4 ml-2 rotate-180" />
                </button>
              )}
            </div>
          </div>
        </div>
      );
    }